name: TechUnity API CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  ECS_CLUSTER: techunity-cluster
  ECS_SERVICE: techunity-api-service
  ECS_REPOSITORY: techunity-api
  ECS_TASK_DEFINITION_API: .aws/task-def-api.json

permissions:
    id-token: write
    contents: read

jobs:
  # Test/Build
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      - name: Build an Image
        run: docker image build -t temp_techunity-api-image:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker image tag temp_techunity-api-image:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{github.sha}}
          docker image push $ECR_REGISTRY/$ECR_REPOSITORY:${{github.sha}}
          echo $ECR_REGISTRY/$ECR_REPOSITORY:${{github.sha}} > api-image-uri.txt

# Deploy
